# Generated by Django 5.2.5 on 2025-08-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh', models.CharField(max_length=100, verbose_name='中文名稱')),
                ('name_en', models.CharField(max_length=100, verbose_name='英文名稱')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='圖片路徑')),
                ('dosage', models.TextField(verbose_name='用法用量')),
                ('side_effects', models.JSONField(default=list, verbose_name='副作用')),
                ('package_insert', models.URLField(blank=True, null=True, verbose_name='仿單連結')),
                ('director_dosage', models.TextField(blank=True, null=True, verbose_name='院長建議劑量')),
                ('storage_location', models.CharField(blank=True, max_length=50, null=True, verbose_name='儲存位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '藥物',
                'verbose_name_plural': '藥物',
                'ordering': ['id'],
            },
        ),
    ]
